version: "3.1"

services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER:  postgres
            POSTGRES_DB: postgres
            TZ: Asia/Shanghai
        volumes:
            - ../data/pgsql-data:/var/lib/postgresql
        ports:
            - 5432:5432

    redis:
        image: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        restart: always
        volumes:
            - ../data/redis-data:/data
            - ../conf:/usr/local/etc/redis
        ports:
            - 6379:6379

    # Use root/root as user/password credentials
    mysql:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ../data/mysql-data:/var/lib/mysql
        ports:
            - 3306:3306

    # mysql admin back office
    mysql-adminer:
        image: adminer
        restart: always
        ports:
            - 3307:8080
